### ISSUE TITLE
Expose the blosc2 metalayer functions

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/cat4py#10]
The use might want to use a new blosc2 metalayer for storing things like types or others, so we need to expose the [metalayer API](https://blosc-doc.readthedocs.io/en/latest/c-blosc2_api.html#metalayer-functions) to cat4py.  It would be nice to add an example on adding layers and updating them directly from Python.

**Comment by aleix11alcacer** [comment]
What do you think if we do it as in the example below (passing metalayers in kargs)?
```python
import cat4py as cat
import numpy as np
import os
from itertools import zip_longest as lzip

pshape = (5, 5)
shape = (10, 10)
filename = "meta-array.cat"

dtype = np.complex128
itemsize = np.dtype(dtype).itemsize

# Create a numpy array
nparray = np.arange(int(np.prod(shape)), dtype=dtype).reshape(shape)

# Create a caterva array from a numpy array
a = cat.from_numpy(nparray, pshape, itemsize=itemsize)

# Create an empty caterva array (on disk)
b = cat.empty(shape, pshape, filename, itemsize=itemsize, metalayers={"numpy": {"dtype": "complex128"}})

assert(b.has_metalayer("numpy") is True)

assert(b.get_metalayer("numpy") == {b"dtype": b"complex128"})

# Fill an empty caterva array using a block iterator
for block, info in b.iter_write(dtype):
    block[:] = nparray[info.slice]

# Remove file on disk
os.remove(filename)
```

**Comment by FrancescAlted** [comment]
I am working towards attaching the metalayers directly to schunks instead of frames.  Meanwhile, I think this is pretty good for now.

**Comment by FrancescAlted** [comment]
@aleix11alcacer I have implemented the new metalayer capabilities in https://github.com/Blosc/c-blosc2/pull/75.  Look at the [frame-metalayers.c](https://github.com/Blosc/c-blosc2/pull/75/files#diff-3a42bf15375163064eb887b7568e31b4) example so as to see how to use the new API.

Could you try the `ml2schunk` and tell me if that would work for you?  My plan is to merge this soon in c-blosc2, so your feedback is appreciated.
