### ISSUE TITLE
Rename container classes: ndarray and ndtarray

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/cat4py#21]
After some discussion between @aleix11alcacer and @FrancescAlted,, they decided that one want to keep two main data containers in cat4py:

* `ndarray` -> holds n-dimensional data that is *typeless*.  This will replace current `tlarray`.
* `ndtarray` -> holds n-dimensional data that is *typed*.  This will replace current `nparray`.

Ideally, `ndtarray` should be a class that inherits from ndarray, with added functionality for serializing and deserializing types.  One can even go an step further and recognize `numpy.dtype` types and be able to come up with automatic serialize/deserialize whenever these are recognized.

**Comment by aleix11alcacer** [comment]
Fixed in #29
