### ISSUE TITLE
Support the buffer and/or array interfaces in a plainbuffer caterva array 

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/cat4py#22]
An `ndarray`  that is backed by a plainbuffer should implement the `buffer` interface so as to be able to reuse its data without an additional copy.

Similarly, an `ndtarray` that is backed by a plainbuffer should implement the `__array_interface` so as to be able to be used in scenarios where a numpy-compatible object is expected so that a copy is avoided.

**Comment by aleix11alcacer** [comment]
Fixed in #29
