### ISSUE TITLE
__getitem__() vs getslice()

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/cat4py#23]
With the new `ndarray` and `ndtarray` containers (see #21), we want to implement two different kinds of slicing operation:

* `__getitem__()`: returns a plain-buffer caterva array supporting the buffer interface for the `ndarray` objects and the  `__array_interface__` for `ndtarray` objects (See #22).

* `getslice()`: returns a `ndarray` or `ndtarray` (depending on which original object is being sliced) object.  By default, `getslice()` will return an object with the same properties than the original `ndarray` or `ndtarray` container, but in addition, it will honor additional `kwargs` that are typically used in cat4py constructors in order to taylor the resulting container.

**Comment by aleix11alcacer** [comment]
Fixed in #29
