### ISSUE TITLE
Compilation problem

### ISSUE THREAD

**Issue by piby2** [Blosc/cat4py#24]
Hi.
I downloaded and compiled c-blosc2 and caterva by following these 3 commands,

git clone https://github.com/Blosc/cat4py
git submodule init
git submodule update --recursive --remote 

My cmake version is 3.15.3, gcc 4.8.5, numpy 1.18.2, 

I installed both of them to a separate directory (no root access), and tried this,
CFLAGS=-O0 python setup.py build_ext -i --blosc2=/home/username/install/ --caterva=/home/username/install

I got bunch of errors like,
cat4py/container_ext.c:1287:3: error: unknown type name ‘caterva_ctx_t’
   caterva_ctx_t *_ctx;

cat4py/container_ext.c:2270:54: error: unknown type name ‘caterva_dims_t’
 static PyObject* __pyx_convert__to_py_caterva_dims_t(caterva_dims_t s);

cat4py/container_ext.c:2526:1: error: unknown type name ‘caterva_dims_t’
 static caterva_dims_t __pyx_convert__from_py_caterva_dims_t(PyObject *); /*proto*/

cat4py/container_ext.c:13911:3: error: unknown type name ‘caterva_dims_t’
   caterva_dims_t __pyx_t_6;

Most of the errors are regarding caterva_ctx_t and  caterva_dims_t being undeclared.

Any suggestion? Thank you.

**Comment by aleix11alcacer** [comment]
Hi @piby2 ,

it seems that you are linking a version of Caterva incompatible with the version of cat4py. We are still in the alpha stage, so we are updating the code many more times than we would like.

Regarding the installation of cat4py, you can use the submodules that the package includes by itself, without linking cat4py with external builds.
```
CFLAGS=-O0 python setup.py build_ext -i
```

However, today a new pull request has been merged with master. In this, the package compilation has been improved, the API has been changed a bit and multidimensionality has been added to the blocks. This new multidimensionality greatly increases the reading performance of the container.

For all this, I recommend that you clone the project again:
```
git clone --recurse-submodules https://github.com/Blosc/cat4py
```
and compile it using scikit-build:
```
python setup.py build_ext --build-type=RelWithDebInfo
```
To check the installation, run:
```
PYTHONPATH=. pytest
```

I hope I've helped :)

**Comment by piby2** [comment]
Thank you. CFLAGS="-O0 -std=c99" worked.
