### ISSUE TITLE
The binder demo does not work

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/cat4py#27]
After clicking on the binder badge in the README, I was not able to run the notebook: https://mybinder.org/v2/gh/Blosc/cat4py/master?filepath=notebooks%2Fcaterva-demo.ipynb

Maybe we need to update the installaltion process or something?

**Comment by aleix11alcacer** [comment]
Gracias por reportar este problema. Esto se arreglará en #28 .

**Comment by aleix11alcacer** [comment]
Thank you for reporting this problem. This will be fixed in #28.
