### ISSUE TITLE
Implement an Array object

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/cat4py#7]
This should be a subclass of `Container`, with a numpy dtype stored in a metalayer, and an additional `__array__` method for better compatibility with the ecosystem.

Its methods should overload the existing ones in `Container`, but using the new `self.dtype` by default.

**Comment by FrancescAlted** [comment]
For the time being, and in order to avoid conveying the idea that cat4py could be used to store all kind of numpy objects, it would be better if we can produce a working example for simple types (suggestion: `examples/persist_numpy.py`).

We can complete the example with a tutorial (a jupyter notebook in the same examples directory would be fine for now) where we show how to get slices of serialized numpy arrays in caterva, and how the `Array` object can work very similarly to a native NumPy array via the help of ``__array__`` and other [special methods](https://docs.scipy.org/doc/numpy/reference/arrays.classes.html).

Also, #10 must be completed before proceeding with this one because we need to use a metalayer in order to store the dtype information in a caterva container.

**Comment by aleix11alcacer** [comment]
In [this jupyter notebook](https://github.com/Blosc/cat4py/blob/metalayer/notebooks/subclassing.ipynb) there is a first version of the Array object. Make sanse?

**Comment by aleix11alcacer** [comment]
An example that measures the performance of getting a slice against numpy has been added.

**Comment by aleix11alcacer** [comment]
Fixed in #29
